### ISSUE TITLE
CRuby 3.4 gems includes pstore 0.1.4 but it has no release

### ISSUE THREAD

**Issue by headius** [ruby/pstore#15]
The pstore.rb in CRuby stdlib says `VERSION = "0.1.4"` but that is not a released version. I am not sure whether this repository and the pstore.rb in ruby/ruby are in sync.

We need a release of the 0.1.4 gem to be able to install that in JRuby's build.

**Comment by hsbt** [comment]
Thanks. Trusted publisher did fail to release 0.1.4.

I will release 0.1.4 again at next week.

**Comment by hsbt** [comment]
@headius I fixed some issues on this repository and released `v0.1.4`

* https://rubygems.org/gems/pstore/versions/0.1.4
* https://github.com/ruby/pstore/releases/tag/v0.1.4

**Comment by headius** [comment]
@hsbt Thank you for moving on this quickly! Perhaps you should file a bug report to RubyGems about Trusted Publisher not working correctly?

**Comment by hsbt** [comment]
The issue of this repository is not rubygems's one. 

If you interest that, could you look https://github.com/sigstore/sigstore-ruby/issues/189 and https://github.com/jruby/jruby-openssl/issues/298?

**Comment by headius** [comment]
@hsbt Thank you for pointing those out... they will be fixed, but I'm not sure when we will have the resources.
